cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #89b4fa
url_color             #74c7ec

color0   #181825
color1   #ff709e
color2   #74ec81
color3   #fff670
color4   #57b6e0
color5   #074d6d
color6   #74c7ec
color7   #e8f3f7
color8   #8d9599
color9   #ff9dbd
color10  #a4ffae
color11  #fff9a4
color12  #90ddff
color13  #a4e3ff
color14  #c4edff
color15  #f8fcff
