[config.wallpaper]
command = "awww img --transition-type fade --transition-duration 1.2 {{image}}"
set = true


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
#post_hook = 'pkill -SIGUSR2 waybar'
post_hook = 'bash /home/swq/.config/matugen/scripts/theme_flush.sh 2>&1'